### PR TITLE
Display a button to request data refresh for last query

### LINKED ISSUE #22: Add a refresh button at the end of the response
Some users repeatedly request the same prognosis at short intervals, just to keep an eye on it. To make it easier for them, each response has to have a button in the end, which the user can press in order to get a fresh set of ETAs.

This will save them a bunch of clicks and taps, which is a major usability improvement for those who use it on a phone.

### PR DESCRIPTION
**Pull request by PlugaruT**
Should fix #22 
And it looks like this:
image

### CODE REVIEW

**Comment by PlugaruT** [comment]
@roata :point_up:

**Comment by roata** [comment]
Thanks, this looks good, I like it that updates the existing message instead of sending a new one, this is really cool!

**Comment by roata** [comment]
How about a minor tweak in the UX?

image


If we use such a 3-button layout, then the response will be more compact (which is good, considering that people use this on their phones).

**Comment by PlugaruT** [comment]
> How about a minor tweak in the UX?
> 
> image
> 
> 
> If we use such a 3-button layout, then the response will be more compact (which is good, considering that people use this on their phones).

Yes, looks good. Gonna think how to do it.

**Pull request merged**
