### PR TITLE
Add support for pipenv

### PR DESCRIPTION
**Pull request by PlugaruT**
- Include `pipenv` for easy venv management and dependency versions. Also, it's easier to separate prod env dependencies and dev env dependencies.
 - Also, I've included `black` code formater and also format all `.py` files. 
Why `black`? Because there's not much to debate on about the way the formatter is formatting the code, except for the line length which is by default 88 chars.

### CODE REVIEW

**Comment by unrevised6419** [comment]
Point 2 may be related to this one #2

**Comment by roata** [comment]
Thank you for your contribution! While I myself don't like some of the defaults `black` enforces (as you can see in the quotes I used and the line lengths), I agree that having an enforced standard would be beneficial in the long run, and I am willing to sacrifice my own preferences for that. What line length do you normally use with it? Would 100 be accepted by your conscience?


In any case, you should take a few additional steps to make it better.

1. Add a `Makefile` with the contents shown below
2. Add some remarks to the readme, explaining that one would have to run `make autoformat` and then `make verify`, and examine the output, looking for issues that need to be addressed
3. For bonus points, at some point in the future we might set up some form of CI, and use the `Makefile` there too.



```
# Run black on all the source files, to format them automatically
# according to whatever the authors of black thought would be a
# sensible appearance
autoformat:
	black *.py


# Run a bunch of checks, to see if there are any obvious deficiencies
# in the code.
verify:
	flake8 *.py
	pylint --rcfile=.pylintrc *.py
	bandit *.py
```

**Comment by unrevised6419** [comment]
Maybe to use a git hook? Write code how you want, on commit is autoformated.
https://github.com/ygpedroso/python-githooks

PS. This should go into another issue.

**Comment by PlugaruT** [comment]
@roata 
Regarding the line length, I don't have a strong feeling about it, I'm ok with setting the length to be 100.
Will push the updates with the `Makefile` soon.

**Comment by roata** [comment]
@PlugaruT, how do you want to be credited in the docs? Under what name?

**Comment by PlugaruT** [comment]
I'm already in the contributors list of the repo...I'd like to leave it like this :)

**Pull request merged**
