### PR TITLE
Fix user feedback collection

### PR DESCRIPTION
**Pull request by PlugaruT**
- Remove some dead code and unused declared variables.
 - Also, remove commented code, we have git history and always can revert :)

### CODE REVIEW

**Comment by roata** [comment]
Thanks for the effort, I have a few requests that have to be addressed before this can be merged.

**Logs**
The logging statements are there to make it easier for new contributors to see what kind of data goes into the function, and the sequence in which functions are called. They're a way to "watch the pulse" of the program.

I commented them, but a better solution would be to:

1. re-enable them (leaving the level at `debug`)
2. adding a new config option to change the verbosity of the log
3. leave it at `info` by default

Thus, we get to keep the debug statements there, but also reduce the `stdout` clutter by default. After this, I will return some other log statements that I personally find useful (and those "unused variables" will start making sense:-)


**The "route 30" rule**
I see that you've added `SUPPORTED_ROUTES = ["30",]`, which is a good idea. However, I have to reveal some of the background of what happened before I uploaded the code to Github.

It looked exactly like you did it. Then, I changed it such that the list of supported routes would be built automatically, based on the files in `res/routes/*.csv`. Everything was fine, until I added support for route 32. The trouble with it is that it turned out to _not_ be fully implemented in the upstream backend that publishes the ETA data over MQTT (apparently, some stations were moved to different locations, so the calculations are not right). I chose to "temporarily" skip it with that `if`, instead of deleting `32.csv`. 

This is not reflected in the project history, because I had to squash all the old commits, in order to protect the identity of those who contributed to this code in the past. So, the right thing to do is:

1. completely remove the temporary `if route_name != "30": continue`
2. move `32.csv` to another directory, let's make it `res/drafts`

The reason to have this CSV file in there, is because this way some people can contribute by populating the CSV files with data (i.e., not programming, but still very useful work). There's a more complex format that will be used in the future, which includes the coordinates of each station - calculating those values is a huge pain in the neck, and that's the reason why we still don't have route 32, even though all the logic is written, and all the hardware is installed on those trolleybuses.

**Feedback feature**
Good catch! I was surprised at first, because the feedback feature works in the bot that is currently deployed in production, so I didn't understand what problem you referred to. Upon closer inspection I realized that I have deleted `self` by mistake from the version that was published on Github.

The Github version will be deployed once we have some actual features (so far all the contributions were about documentation, code quality and maintenance).

**Comment by unrevised6419** [comment]
I am new to Python world.
It will be a good idea to extract `Infobot` class to another file?  
And use `main.py` just as starting point?

ps: `Infobot` or `InfoBot` should be the class name?

**Comment by PlugaruT** [comment]
@roata, I was making changes based on the code. Thanks for the insights tho, will do the changes

**Comment by roata** [comment]
@iamandrewluca, 

Moving it to another file is a generally good idea, especially when you have multiple classes. In this case, we don't have "a main file with a class in it", but "a class with a `__main__` entry point". Adding such an entry point is a typical pattern in Python, it is handy when you want to run some code without invoking other parts of an ecosystem (e.g., for testing).

When I first wrote it, the entry point was just a few lines of code (hence "class with an entry point", rather than "an entry point with a class:-), so there's no cognitive burden that it brings to the table. It looks a bit bigger now, after `black` has added some line-breaks which I would have never added by myself; yet it is still logically isolated, and doesn't get in the way.

If this entry point gets complex in the future (for instance, we add command line switches), then moving it into a separate file would definitely make sense. In the current state of things, it is an insignificant matter.
I spent more time writing this comment (than it would have taken to move it out) because I want you to know that "măcar cineva te aude în casa asta".


As for the second point, it is a matter of culture :-) Someone treats this word as a single entity, whereas someone else sees it as a complex one. For example, do you treat the word `фоторобот` as `Fotorobot` (a synthesized photo of a suspect), as `FotoRobot` (some sort of machine that makes photos)?  Or in Romanian, would you call your class `Feribot` or `FeriBot`?

You are right, the canons of Python say that class names should be CamelCase and start with a capital. In this particular case, I just treated `infobot` as a single word (despite being aware of the etymology*).




* 'Robot' comes from 'Robotnik' in Czech.

**Comment by roata** [comment]
@PlugaruT, are you still working on this? There are some new features on their way, but first I'd like to ensure that all existing issues are addressed.

**Comment by PlugaruT** [comment]
Yes, I'll push some changes today or tomorrow 😬

**Comment by PlugaruT** [comment]
@roata hope it's 👌

**Comment by roata** [comment]
The logging part is much nicer than I expected, thanks for putting in the extra effort!

**Pull request merged**
